# Image used
image:
  - Visual Studio 2019
  - Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor"
  - sh: ./build.sh --target="AppVeyor"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
- tools -> build.ps1, global.json